name: Build Test

on:
  push:

jobs:
  build-native-components:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download webOS NDK
      run: wget -q https://github.com/webosbrew/meta-lg-webos-ndk/releases/download/1.0.g-rev.4/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -P ${{github.workspace}}/temp

    - name: Install webOS NDK
      run: chmod 755 ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh && sudo ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -y

    - name: Initialize NDK Environments
      run: env -i bash -c '. /opt/webos-sdk-x86_64/1.0.g/environment-setup-armv7a-neon-webos-linux-gnueabi && env' >> $GITHUB_ENV

    - name: Create build directories
      run: |
        mkdir ${{github.workspace}}/hyperion-webos_libvtcapture/build
#       mkdir ${{github.workspace}}/hyperion-webos/build

#    - name: Build hyperion-webos
#      working-directory: ${{github.workspace}}/hyperion-webos/build
#      shell: bash
#      run: cmake .. && make

    - name: Build hyperion-webos_libvtcapture
      working-directory: ${{github.workspace}}/hyperion-webos_libvtcapture/build
      shell: bash
      run: cmake .. && make
    
    - name: List files
      run: find .

    - name: Upload native components artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webos_libs
        path: |
          ${{github.workspace}}/hyperion-webos_libvtcapture/build/hyperion-webos_libvtcapture
#         ${{github.workspace}}/hyperion-webos/build/hyperion-webos

  build-piccap:
    runs-on: ubuntu-latest
    needs: build-native-components

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install webOS CLI
        run: |
          sudo npm install -g @webosose/ares-cli

      - name: Install dependencies
        working-directory: ${{github.workspace}}/service
        run: npm install

      - name: Build App
        working-directory: ${{github.workspace}}/service
        run: npm run build

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: webos_libs
          path: webos_libs

      - name: List files
        run: find .

      - name: Copy native module
        run: |
          cp webos_libs/hyperion-webos_libvtcapture ./service/piccap.service/hyperion-webos_libvtcapture
#          cp webos_libs/hyperion-webos ./service/piccap.service/hyperion-webos

      - name: Package
        run: mkdir build && ares-package ./piccap ./service/piccap.service -o ./build

      - name: List files
        run: find . && find ./build

      - name: Upload piccap ipk
        uses: actions/upload-artifact@v2
        with:
          name: piccap_ipk
          path: |
            build/*.ipk